http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.enabled: true
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Performance settings
queue.type: memory
queue.max_events: 1000
queue.max_bytes: 1gb

# Logging
log.level: info
